services:
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
        - POSTGRES_DB=company
        # You should definitely change the password in production
        - POSTGRES_PASSWORD=secret
        - POSTGRES_USER=default
    volumes:
      - db_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"

volumes:
  db_data:
