<?php

namespace App\Exception;

use App\Exception\PublishedMessageException;
use App\Exception\UserInputException;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpKernel\Exception\HttpException;

/**
 *
 */
class AccessDeniedException extends HttpException
{

    /**
     * @var string
     */
    protected $message = "Access denied.";

    /**
     * @param string $message
     * @param \Throwable|null $previous
     * @param int $code
     * @param array $headers
     */
    public function __construct(string $message = '', ?\Throwable $previous = null, int $code = 0, array $headers = [])
    {
        parent::__construct(JsonResponse::HTTP_UNAUTHORIZED, $this->message, $previous, $headers, $code);
    }

    /**
     * @return int
     */
    public function getStatusCode(): int
    {
        return JsonResponse::HTTP_UNAUTHORIZED; // TODO: Change the autogenerated stub
    }
}
